# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

'on':
  push:
    branches:
      - dev
    tags: ['v*.*.*']

env:
  GIT_LFS_SKIP_SMUDGE: 1 # Don't pull LFS files
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
jobs:
  deploy:
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@v2.5.0
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      # Optional inputs can be passed here
      org: epfl-eesd
      repo: mmsdb
      build_context: '["./backend", "./frontend"]' # Optional"
